/* generated by @ankhorage/orchestrator-module-expo-google-fonts */
import React, { useEffect, useState } from "react";
import { loadAsync } from "expo-font";

import { FontProvider as SurfaceFontProvider } from "@ankhorage/surface";

import { fontAssets } from "./fonts.generated";

export interface GoogleFontsProviderProps {
  children: React.ReactNode;
  activeFontId?: string | null;
}

export function GoogleFontsProvider(props: GoogleFontsProviderProps) {
  const { children, activeFontId: activeFontIdProp } = props;
  const [fontsLoaded, setFontsLoaded] = useState(false);

  let activeFontId = activeFontIdProp ?? null;

  if (activeFontId == null) {
    try {
      const ankhConfig = require("@root/ankh.config.json");
      activeFontId = ankhConfig?.typography?.activeFontId ?? null;
    } catch (error) {
      console.warn("[GoogleFonts] Unable to load @root/ankh.config.json:", error);
    }
  }

  useEffect(() => {
    async function loadFonts() {
      try {
        if (Object.keys(fontAssets).length > 0) {
          await loadAsync(fontAssets);
        }
      } catch (error) {
        console.warn("[GoogleFonts] Failed to load fonts:", error);
      } finally {
        setFontsLoaded(true);
      }
    }

    void loadFonts();
  }, []);

  return (
    <SurfaceFontProvider fontsLoaded={fontsLoaded} activeFontId={activeFontId}>
      {children}
    </SurfaceFontProvider>
  );
}
