/* generated by @ankhorage/orchestrator-module-expo-google-fonts */
import type { FontSource } from "expo-font";

__FONT_IMPORTS__

export const fontAssets: Record<string, FontSource> = {
__FONT_ASSET_LINES__
};
